'use client';

const PROVINCES_ND293 = [
    { name: '1. Thành phố Hà Nội', detail: 'Vùng I: gồm các phường Hoàn Kiếm, Ba Đình, Ngọc Hà, Giảng Võ, Hồ Tây, Liên Mạc, Ô Chợ Dừa, Hàng Ngã, Linh Nam, Vĩnh Hưng, Tương Mai, Đình Công, Hoàng Liệt, Yên Sở, Thanh Xuân, Khương Đình, Phương Liệt, Cầu Giấy, Nghĩa Đô, Yên Hoa, Tứ Liên, Thụy Khuê, Xuân Đỉnh, Đông Ngạc, Từ Liêm, Xuân Phương, Tây Mỗ, Long Biên, Bồ Đề, Việt Hưng, Phúc Lợi, Hà Đông, Dương Nội, Yên Nghĩa, Phú Lương, Kiến Hưng, Thanh Liệt, Chương Mỹ, Sơn Tây, Tùng Thiện, Tây Tựu, Phú Diễn, Thượng Phúc, Thường Tín, Hồng Vân, Phú Xuyên, Thanh Oai, Bình Minh, Tam Hưng, Phú Nghĩa, Xuân Mai, Trần Phú, Hòa Phú, Quảng Bị, Yên Bài, Thạch Thất, Hoài Đức, Vân Canh, Song Phương, An Khánh, Gia Lâm, Thuận An, Bát Tràng, Phù Đổng, Đông Anh, Phú Thịnh, Thiên Lộc, Vĩnh Thanh, Mê Linh, Tráng Việt, Yên Lãng, Tiến Thắng, Quang Minh, Sóc Sơn, Đa Phúc, Nội Bài, Trung Giã, Kim Anh, Ô Diên, Vinh Liêm, Liên Minh.\nVùng II: gồm các xã, phường còn lại.' },
    { name: '2. Tỉnh Cao Bằng', detail: 'Vùng III: gồm các phường Thúc Phán, Nùng Trí Cao, Tân Giang.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '3. Tỉnh Tuyên Quang', detail: 'Vùng III: gồm các phường Mỵ Lâm, Minh Xuân, Nông Tiến, An Tường, Bình Thuận, Hà Giang 1, Hà Giang 2 và xã Ngọc Đường.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '4. Tỉnh Điện Biên', detail: 'Vùng III: gồm các phường Điện Biên Phủ, Mường Thanh và xã Mường Phăng, Nà Tấu.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '5. Tỉnh Lai Châu', detail: 'Vùng III: gồm các phường Tân Phong, Đoàn Kết.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '6. Tỉnh Sơn La', detail: 'Vùng III: gồm các phường Tô Hiệu, Chiềng An, Chiềng Cơi, Chiềng Sinh.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '7. Tỉnh Lào Cai', detail: 'Vùng II: gồm các phường Cam Đường, Lào Cai và các xã Cốc San, Hợp Thành, Gia Phú.\nVùng III: gồm các phường Văn Phú, Yên Bái, Nam Cường, Âu Lâu, Sa Pa và các xã Phong Hải, Xuân Quang, Bảo Thắng, Tằng Loỏng, Mường Bo, Bản Hồ, Tả Phìn, Tả Van, Ngũ Chỉ Sơn.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '8. Tỉnh Thái Nguyên', detail: 'Vùng II: gồm các phường Phan Đình Phùng, Linh Sơn, Tích Lương, Gia Sàng, Quyết Thắng, Quan Triều, Phố Yên, Vạn Xuân, Trung Thành, Phúc Thuận, Sông Công, Bá Xuyên, Bách Quang và các xã Tân Cương, Đại Phúc, Thành Công.\nVùng III: gồm các phường Đức Xuân, Bắc Kạn và các xã Đại Từ, Đức Lương, Phú Thịnh, La Bằng, Phú Lạc, An Khánh, Quân Chu, Vạn Phú, Phú Bình, Đồng Hỷ, Quang Sơn, Trại Cau, Nam Hòa, Văn Hán, Văn Lăng, Phú Lương, Võ Tranh, Yên Trạch, Hợp Thành, Phong Quang.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '9. Tỉnh Lạng Sơn', detail: 'Vùng III: gồm các phường Tam Thanh, Lương Văn Trị, Kỳ Lừa, Đông Kinh.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '10. Tỉnh Quảng Ninh', detail: 'Vùng I: gồm các phường An Sinh, Đồng Triều, Bình Khê, Mạo Khê, Hoàng Quế, Yên Tử, Vàng Danh, Uông Bí, Đông Mai, Hiệp Hòa, Quảng Yên, Hà An, Phong Cốc, Liên Hòa, Tuần Châu, Việt Hưng, Bãi Cháy, Hà Tu, Hà Lầm, Cao Xanh, Hồng Gai, Hạ Long, Hoành Bồ, Mộng Cái 1, Mộng Cái 2, Mộng Cái 3 và các xã Quảng La, Thống Nhất, Hải Sơn, Hải Ninh, Vĩnh Thực.\nVùng II: gồm các phường Mộng Dương, Quang Hanh, Cẩm Phả, Cửa Ông và xã Hải Hòa.\nVùng III: gồm các xã Tiên Yên, Điền Xá, Đồng Ngũ, Hải Lạng, Quảng Tân, Đầm Hà, Quảng Hà, Đường Hoa, Quảng Đức, Cái Chiên và đặc khu Vân Đồn.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '11. Tỉnh Bắc Ninh', detail: 'Vùng II: gồm nhiều phường Kinh Bắc, Thuận Thành, Quế Võ, Yên Phong, Tiền Du và các xã lân cận.\nVùng III: gồm các xã Lạng Giang, Mỹ Thái, Kép, Tân Dĩnh, Tiến Lực, Tân Yên, Ngọc Thiện, Nhã Nam, Phúc Hòa, Quang Trung, Hợp Thịnh, Hiệp Hòa, Hoàng Vân, Xuân Cẩm.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '12. Tỉnh Phú Thọ', detail: 'Vùng II: gồm các phường Việt Trì, Nông Trang, Thanh Miếu, Văn Phú, Vĩnh Phúc, Vĩnh Yên, Phúc Yên, Xuân Hòa, Hòa Bình, Kỳ Sơn, Tần Hòa, Thống Nhất và các xã Hy Cương, Yên Lạc, Tề Lỗ, Liên Châu, Bình Xuyên, Lương Sơn, Cao Đường, Liễn Sơn, Thịnh Minh.\nVùng III: gồm các phường Phong Châu, Phú Thọ, Âu Cơ và các xã Lâm Thao, Xuân Lũng, Phụng Nguyên, Phù Ninh, Thanh Ba, Đồng Thịnh và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '13. Thành phố Hải Phòng', detail: 'Vùng I: gồm các phường Thủy Nguyên, Thiên Hương, Hòa Bình, Nam Triệu, Bạch Đằng, Lưu Kiếm, Lê Ích Mộc, Hồng Bảng, Hồng An, Ngô Quyền, Gia Viên, Lê Chân, An Biên, Hải An, Đồng Hải, Kiến An, Nam Đố, Đồ Sơn, Hưng Đạo, Dương Kinh, An Dương, An Hải, An Phong, Việt Hòa, Thành Đông, Nam Đồng, Tân Hưng, Thạch Khôi, Tứ Minh, Ái Quốc, Chí Linh, Trần Hưng Đạo, Nguyễn Trãi và nhiều phường khác.\nVùng II: gồm các xã Thanh Hà, Hà Tây, Hà Bắc, Hà Nam, Hà Đông, Ninh Giang, Vĩnh Lại, Tân An, Hồng Châu, Thanh Miện và đặc khu Bạch Long Vĩ.\nVùng III: gồm các xã, phường còn lại.' },
    { name: '14. Tỉnh Hưng Yên', detail: 'Vùng II: gồm các phường Phố Hiến, Sơn Nam, Hồng Châu, Mỹ Hào, Đường Hào, Thượng Hồng, Thái Bình, Trần Hưng Đạo, Trà Lý, Vũ Phúc và các xã Tân Hưng, Yên Mỹ, Như Quỳnh, Lạc Đạo, Đại Đồng, Văn Giang, Mễ Sở.\nVùng III: gồm các xã Hoàng Hoa Thám, Tiền Lữ, Tiên Hoa, Quang Hưng, Đoàn Đào, Tiến Thắng, Tống Trân, Lương Bằng, Nghĩa Dân, Hiệp Cường, Đức Hợp, Ân Thi và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '15. Tỉnh Ninh Bình', detail: 'Vùng II: gồm các phường Tây Hoa Lư, Hoa Lư, Nam Hoa Lư, Đông Hoa Lư, Nam Định, Thiên Trường, Đông A, Vị Khê, Thành Nam, Trường Thi, Hồng Quang, Mỹ Lộc.\nVùng III: gồm các phường Tam Điệp, Yên Sơn, Trung Sơn, Yên Thắng và nhiều xã thuộc Ninh Bình, Nam Định, Hà Nam.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '16. Tỉnh Thanh Hóa', detail: 'Vùng II: gồm các phường Hạc Thành, Quảng Phú, Đông Quang, Đông Sơn, Đông Tiến, Hàm Rồng, Nguyệt Viên, Sầm Sơn, Nam Sầm Sơn, Bỉm Sơn, Quảng Trung, Ngọc Sơn, Tân Đàn, Hải Linh và nhiều xã lân cận.\nVùng III: gồm các xã Hà Trung, Tống Sơn, Hà Long, Hoạt Giang, Linh Toại, Triệu Lộc, Đồng Thành, Hậu Lộc, Hoa Lộc, Ngư Lộc, Nga Sơn, Nga Thắng và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '17. Tỉnh Nghệ An', detail: 'Vùng II: gồm các phường Trường Vinh, Thành Vinh, Vinh Hưng, Vinh Phú, Vinh Lộc, Cửa Lò và các xã Hưng Nguyên, Yên Trung và nhiều xã lân cận.\nVùng III: gồm các phường Hoàng Mai, Tân Mai, Quỳnh Mai, Thái Hòa, Tây Hiếu và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '18. Tỉnh Hà Tĩnh', detail: 'Vùng III: gồm các phường Sông Trì, Hải Ninh, Hoành Sơn, Vũng Áng, Thành Sen, Trần Phú, Hà Huy Tập và các xã Thạch Lạc, Đồng Tiến, Thạch Khê, Cẩm Bình, Kỳ Hoa.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '19. Tỉnh Quảng Trị', detail: 'Vùng II: gồm các phường Đồng Hới, Đồng Thuận, Đồng Sơn.\nVùng III: gồm các phường Đồng Hà, Nam Đồng Hà, Ba Đồn, Bắc Gianh và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '20. Thành phố Huế', detail: 'Vùng II: gồm các phường Thuận An, Hóa Châu, Mỹ Thượng, Vỹ Dạ, Thuận Hóa, An Cựu, Thủy Xuân, Kim Long, Hương An, Phú Xuân, Dương Nổ.\nVùng III: gồm các phường Phong Điền, Phong Thái, Phong Định, Phong Phú, Phong Quảng, Hương Trà, Kim Trà, Hương Thủy, Phú Bài, Thanh Thủy và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '21. Thành phố Đà Nẵng', detail: 'Vùng I: gồm các phường Hải Châu, Hòa Cường, Thanh Khê, An Khê, An Hải, Sơn Trà, Ngũ Hành Sơn, Hòa Khánh, Hải Vân, Liên Chiểu, Cẩm Lệ, Hòa Xuân, Tam Kỳ, Quảng Phú, Hội An và các xã Hòa Vang, Hòa Tiến, Bà Nà, Tân Hiệp và đặc khu Hoàng Sa.\nVùng II: gồm các phường Điện Bàn và nhiều xã Núi Thành, Quế Sơn và các xã lân cận.\nVùng III: gồm các xã, phường còn lại.' },
    { name: '22. Tỉnh Quảng Ngãi', detail: 'Vùng III: gồm các phường Trương Quang Trọng, Cẩm Thành, Nghĩa Lộ, Kon Tum, Đắk Cấm, Đắk Bla và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '23. Tỉnh Gia Lai', detail: 'Vùng III: gồm các phường Quy Nhơn, Quy Nhơn Đông, Quy Nhơn Tây, Quy Nhơn Nam, Quy Nhơn Bắc, Pleiku, Hội Phú, Thống Nhất, Diên Hồng, An Phú và các xã Biển Hồ, Gào.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '24. Tỉnh Khánh Hòa', detail: 'Vùng II: gồm các phường Nha Trang, Bắc Nha Trang, Tây Nha Trang, Nam Nha Trang, Bắc Cam Ranh, Cam Ranh, Cam Linh, Bà Ngòi, Ninh Hòa, Đồng Ninh Hòa, Hòa Thắng, Phan Rang, Đồng Hải và nhiều xã lân cận.\nVùng III: gồm các xã Đại Lãnh, Tu Bông, Vạn Thắng, Vạn Ninh và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '25. Tỉnh Đắk Lắk', detail: 'Vùng III: gồm các phường Buôn Ma Thuột, Tân An, Tân Lập, Nguyễn Đại, Sông Cầu, Thống Nhất, Ea Kao, Tuy Hòa, Phú Yên, Bình Kiến, Đồng Hòa, Hòa Hiệp và các xã Hòa Phú, Xuân Thọ, Xuân Cảnh, Xuân Lộc, Hòa Xuân.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '26. Tỉnh Lâm Đồng', detail: "Vùng II: gồm các phường Xuân Hương - Đà Lạt, Cam Ly - Đà Lạt, Làm Viên - Đà Lạt, Xuân Trường - Đà Lạt, Lang Biang - Đà Lạt, 1 Bảo Lộc, 2 Bảo Lộc, 3 Bảo Lộc, B' Lao, Hàm Thắng, Bình Thuận, Mũi Né, Phú Thủy, Phan Thiết, Tiến Thành, Tân Xuân và xã Tuyên Quang.\nVùng III: gồm các phường La Gi, Phước Hội, Bắc Gia Nghĩa, Nam Gia Nghĩa, Đồng Gia Nghĩa và các xã Hiệp Thạnh, Đức Trọng, Tà Hine, Tà Năng, Liên Nghĩa, Đinh Văn Lâm Hà, Di Linh, Hòa Ninh, Hòa Bắc, Bình Trang, Bảo Thuận, Gia Hiệp, Sơn Hải, Đồng Giang, La Đạ, Hàm Thuận Bắc, Hàm Thuận Nam, Hồng Sơn, Hàm Liêm, Hàm Thanh, Hàm Kiệm, Tân Thành và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại." },
    { name: '27. Tỉnh Đồng Nai', detail: 'Vùng I: gồm các phường Biên Hòa, Trản Biên, Tam Hiệp, Long Bình, Tràng Dài, Hố Nai, Long Hưng, Bình Lộc, Bảo Vinh, Xuân Lập, Long Khánh, Hàng Gòn và nhiều phường khác.\nVùng II: gồm các phường Minh Hưng, Chơn Thành, Đồng Xoài, Bình Phước và nhiều xã khác.\nVùng III: gồm các phường Thiên Hưng, Hưng Phước, Phú Nghĩa, Đa Kia và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '28. Thành phố Hồ Chí Minh', detail: 'Vùng I: gồm các phường Sài Gòn, Tân Định, Bến Thành, Cầu Ông Lãnh, Bàn Cờ, Xuân Hòa, Nhiều Lộc, Xóm Chiếu, Khánh Hội, Vĩnh Hội, Chợ Quán, An Đông, Chợ Lớn, Bình Tây, Bình Phú, Tân Thuận, Phú Thuận, Tân Mỹ, Tân Hưng, Bình Tân, Gò Vấp, Thủ Đức, Tam Bình, Linh Xuân, Tăng Nhơn Phú, Long Bình, Phước Long, Trường Thọ, Cát Lái, Bình An, Thành phố Thủ Dầu Một, Hóc Môn, Xuân Thới Sơn, Ba Điểm, Nhà Bè, Hiệp Phước và nhiều phường khác.\nVùng II: gồm các phường Bà Rịa, Long Hương, Tam Long và các xã Bình Khánh, An Thời Đông, Cần Giờ, Thạnh An và đặc khu Côn Đảo.\nVùng III: gồm các xã, phường còn lại.' },
    { name: '29. Tỉnh Tây Ninh', detail: 'Vùng I: gồm các phường Long An, Tân An, Khánh Hậu và nhiều xã lân cận.\nVùng II: gồm các phường Kiến Tường, Tân Ninh, Bình Minh, Ninh Thạnh, Long Hoa, Hòa Thành, Thanh Điền, Tráng Bàng, An Tinh, Gò Dầu và nhiều xã khác.\nVùng III: gồm các xã Bình Thành, Thanh Phước, Thanh Hòa, Tân Tây và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '30. Tỉnh Đồng Tháp', detail: 'Vùng II: gồm các phường Mỹ Tho, Đạo Thanh, Mỹ Phong, Thới Sơn, Trung An và nhiều xã lân cận.\nVùng III: gồm các phường Gò Công, Long Thuận, Bình Xuân, Cai Lậy, Nhị Quý, An Bình, Hồng Ngự, Cao Lãnh, Mỹ Ngãi, Mỹ Trà, Sa Đéc và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '31. Tỉnh Vĩnh Long', detail: 'Vùng II: gồm các phường Thanh Đức, Long Châu, Phước Hậu, Tân Hạnh, Tân Ngãi, Bình Minh, Cái Vồn, Đồng Thành, An Hội và nhiều xã lân cận.\nVùng III: gồm các phường Duyên Hải, Trường Long Hòa và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '32. Tỉnh An Giang', detail: 'Vùng II: gồm các phường Long Xuyên, Bình Đức, Mỹ Thới, Châu Đốc, Vĩnh Tế, Vĩnh Thông, Rạch Giá, Hà Tiên và nhiều phường khác.\nVùng III: gồm nhiều xã thuộc Tân Châu, Châu Phú, Thoại Sơn, Kiên Giang và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '33. Thành phố Cần Thơ', detail: 'Vùng II: gồm các phường Phú Lợi, Mỹ Xuyên, Ninh Kiều, Cái Khế, Tân An, An Bình, Thới An Đông, Bình Thủy, Long Tuyến, Cái Răng, Hưng Phú, Ô Môn, Thới Long, Phước Thới, Trung Nhứt, Thốt Nốt, Thuận Hưng, Tân Lộc.\nVùng III: gồm nhiều xã thuộc Vị Thanh, Vị Tân, Đại Thành, Ngã Bảy, Vĩnh Châu, Khánh Hòa, Ngã Năm và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '34. Tỉnh Cà Mau', detail: 'Vùng II: gồm các phường An Xuyên, Lý Văn Lâm, Tân Thành, Hòa Thành, Bạc Liêu, Vĩnh Trạch, Hiệp Thành.\nVùng III: gồm nhiều xã thuộc Giá Rai, Làng Trôn, Ú Minh, Nguyễn Phích, Khánh Lâm, Khánh An và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
];

const PROVINCES_ND73 = [
    { name: '1. Tỉnh Lào Cai', detail: 'Vùng II: gồm các phường Cam Đường, Lào Cai và các xã Cốc San, Hợp Thành, Gia Phú.\nVùng III: gồm các phường Văn Phú, Yên Bái, Nam Cường, Âu Lâu, Sa Pa và các xã Phong Hải, Xuân Quang, Bảo Thắng, Tằng Loỏng, Mường Bo, Bản Hồ, Tả Phìn, Tả Van, Ngũ Chỉ Sơn.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '2. Tỉnh Cao Bằng', detail: 'Vùng III: gồm các phường Thúc Phán, Nùng Trí Cao, Tân Giang.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '3. Tỉnh Điện Biên', detail: 'Vùng III: gồm các phường Điện Biên Phủ, Mường Thanh và xã Mường Phăng, Nà Tấu.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '4. Tỉnh Lai Châu', detail: 'Vùng III: gồm các phường Tân Phong, Đoàn Kết.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '5. Tỉnh Sơn La', detail: 'Vùng III: gồm các phường Tô Hiệu, Chiềng An, Chiềng Cơi, Chiềng Sinh.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '6. Tỉnh Tuyên Quang', detail: 'Vùng III: gồm các phường Mỵ Lâm, Minh Xuân, Nông Tiến, An Tường, Bình Thuận, Hà Giang 1, Hà Giang 2 và xã Ngọc Đường.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '7. Tỉnh Lạng Sơn', detail: 'Vùng III: gồm các phường Tam Thanh, Lương Văn Trị, Hoàng Văn Thụ, Đông Kinh.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '8. Tỉnh Phú Thọ', detail: 'Vùng II: gồm các phường Việt Trì, Nông Trang, Thanh Miếu, Văn Phú, Vĩnh Phúc, Vĩnh Yên, Phúc Yên, Xuân Hòa, Hòa Bình, Kỳ Sơn, Tần Hòa, Thống Nhất và các xã Hy Cương, Yên Lạc, Tề Lỗ, Liên Châu, Bình Xuyên, Lương Sơn, Cao Đường, Liễn Sơn, Thịnh Minh.\nVùng III: gồm các phường Phong Châu, Phú Thọ, Âu Cơ và các xã Lâm Thao, Xuân Lũng, Phụng Nguyên, Phù Ninh, Thanh Ba, Đồng Thịnh và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '9. Tỉnh Quảng Ninh', detail: 'Vùng I: gồm các phường An Sinh, Đồng Triều, Bình Khê, Mạo Khê, Hoàng Quế, Yên Tử, Vàng Danh, Uông Bí, Đông Mai, Hiệp Hòa, Quảng Yên, Hà An, Phong Cốc, Liên Hòa, Tuần Châu, Việt Hưng, Bãi Cháy, Hà Tu, Hà Lầm, Cao Xanh, Hồng Gai, Hạ Long, Hoành Bồ, Mộng Cái 1, Mộng Cái 2, Mộng Cái 3 và các xã Quảng La, Thống Nhất, Hải Sơn, Hải Ninh, Vĩnh Thực.\nVùng II: gồm các phường Mộng Dương, Quang Hanh, Cẩm Phả, Cửa Ông và xã Hải Hòa.\nVùng III: gồm các xã Tiên Yên, Điền Xá, Đồng Ngũ, Hải Lạng, Quảng Tân, Đầm Hà, Quảng Hà, Đường Hoa, Quảng Đức, Cái Chiên và đặc khu Vân Đồn.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '10. Thành phố Hải Phòng', detail: 'Vùng I: gồm các phường Thủy Nguyên, Thiên Hương, Hòa Bình, Nam Triệu, Bạch Đằng, Lưu Kiếm, Lê Ích Mộc, Hồng Bảng, Hồng An, Ngô Quyền, Gia Viên, Lê Chân, An Biên, Hải An, Đồng Hải, Kiến An, Nam Đố, Đồ Sơn, Hưng Đạo, Dương Kinh, An Dương, An Hải và nhiều phường khác.\nVùng II: gồm các xã Thanh Hà, Hà Nam, Ninh Giang, Vĩnh Lại, Tân An, Hồng Châu, Thanh Miện và đặc khu Bạch Long Vĩ.\nVùng III: gồm các xã, phường còn lại.' },
    { name: '11. Tỉnh Hưng Yên', detail: 'Vùng II: gồm các phường Phố Hiến, Sơn Nam, Hồng Châu, Mỹ Hào, Đường Hào, Thượng Hồng, Thái Bình, Trần Hưng Đạo, Trà Lý, Vũ Phúc và các xã Tân Hưng, Yên Mỹ, Như Quỳnh, Lạc Đạo, Đại Đồng, Văn Giang, Mễ Sở.\nVùng III: gồm các xã Hoàng Hoa Thám, Tiền Lữ, Tiên Hoa, Quang Hưng, Đoàn Đào, Tiến Thắng, Tống Trân, Lương Bằng, Nghĩa Dân, Hiệp Cường, Đức Hợp, Ân Thi và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '12. Tỉnh Thái Nguyên', detail: 'Vùng II: gồm các phường Phan Đình Phùng, Linh Sơn, Tích Lương, Gia Sàng, Quyết Thắng, Quan Triều, Phố Yên, Vạn Xuân, Trung Thành, Phúc Thuận, Sông Công, Bá Xuyên, Bách Quang và các xã Tân Cương, Đại Phúc, Thành Công.\nVùng III: gồm các phường Đức Xuân, Bắc Kạn và các xã Đại Từ, Đức Lương, Phú Thịnh, La Bằng, Phú Lạc, An Khánh, Quân Chu, Vạn Phú, Phú Bình, Đồng Hỷ, Quang Sơn, Trại Cau, Nam Hòa, Văn Hán, Văn Lăng, Phú Lương, Võ Tranh, Yên Trạch, Hợp Thành, Phong Quang.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '13. Tỉnh Bắc Ninh', detail: 'Vùng II: gồm nhiều phường Kinh Bắc, Thuận Thành, Quế Võ, Yên Phong, Tiền Du và các xã lân cận.\nVùng III: gồm các xã Lạng Giang, Mỹ Thái, Kép, Tân Dĩnh, Tiến Lực, Tân Yên, Ngọc Thiện, Nhã Nam, Phúc Hòa, Quang Trung, Hợp Thịnh, Hiệp Hòa, Hoàng Vân, Xuân Cẩm.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '14. Thành phố Hà Nội', detail: 'Vùng II: gồm các xã Phương Đức, Chuyên Mỹ, Đại Xuyên, Văn Điển, Ứng Thiên, Hòa Xá, Ứng Hòa, Mỹ Đức, Hồng Sơn, Phúc Sơn, Hương Sơn, Minh Quang, Quảng Oai, Vật Lại, Cổ Đô, Bất Bạt, Suối Hai, Ba Vì, Phúc Thọ, Phúc Lộc, Hát Môn, Đan Phượng.\nVùng I: gồm các xã, phường còn lại.' },
    { name: '15. Tỉnh Ninh Bình', detail: 'Vùng II: gồm các phường Tây Hoa Lư, Hoa Lư, Nam Hoa Lư, Đông Hoa Lư, Nam Định, Thiên Trường, Đông A, Vị Khê, Thành Nam, Trường Thi, Hồng Quang, Mỹ Lộc.\nVùng III: gồm các phường Tam Điệp, Yên Sơn, Trung Sơn, Yên Thắng và nhiều xã thuộc Ninh Bình, Nam Định, Hà Nam.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '16. Tỉnh Thanh Hóa', detail: 'Vùng II: gồm các phường Hạc Thành, Quảng Phú, Đông Quang, Đông Sơn, Đông Tiến, Hàm Rồng, Nguyệt Viên, Sầm Sơn, Nam Sầm Sơn, Bỉm Sơn, Quảng Trung, Ngọc Sơn, Tân Đàn, Hải Linh và nhiều xã lân cận.\nVùng III: gồm các xã Hà Trung, Tống Sơn, Hà Long, Hoạt Giang và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '17. Tỉnh Nghệ An', detail: 'Vùng II: gồm các phường Trường Vinh, Thành Vinh, Vinh Hưng, Vinh Phú, Vinh Lộc, Cửa Lò và các xã Hưng Nguyên, Yên Trung và nhiều xã lân cận.\nVùng III: gồm các phường Hoàng Mai, Tân Mai, Quỳnh Mai, Thái Hòa và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '18. Tỉnh Hà Tĩnh', detail: 'Vùng III: gồm các phường Sông Trì, Hải Ninh, Hoành Sơn, Vũng Áng, Thành Sen, Trần Phú, Hà Huy Tập và các xã Thạch Lạc, Đồng Tiến, Thạch Khê, Cẩm Bình, Kỳ Hoa.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '19. Tỉnh Quảng Trị', detail: 'Vùng II: gồm các phường Đồng Hới, Đồng Thuận, Đồng Sơn.\nVùng III: gồm các phường Đồng Hà, Nam Đồng Hà, Ba Đồn, Bắc Gianh và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '20. Thành phố Huế', detail: 'Vùng II: gồm các phường Thuận An, Hóa Châu, Mỹ Thượng, Vỹ Dạ, Thuận Hóa, An Cựu, Thủy Xuân, Kim Long, Hương An, Phú Xuân, Dương Nổ.\nVùng III: gồm các phường Phong Điền, Phong Thái, Phong Định, Phong Phú, Phong Quảng và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '21. Thành phố Đà Nẵng', detail: 'Vùng I: gồm các phường Hải Châu, Hòa Cường, Thanh Khê, An Khê, An Hải, Sơn Trà, Ngũ Hành Sơn, Hòa Khánh, Hải Vân, Liên Chiểu, Cẩm Lệ, Hòa Xuân, Hội An và nhiều phường khác.\nVùng II: gồm các phường Điện Bàn và nhiều xã khác.\nVùng III: gồm các xã, phường còn lại.' },
    { name: '22. Tỉnh Quảng Ngãi', detail: 'Vùng III: gồm các phường Trương Quang Trọng, Cẩm Thành, Nghĩa Lộ, Kon Tum, Đắk Cấm, Đắk Bla và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '23. Tỉnh Đắk Lắk', detail: 'Vùng III: gồm các phường Buôn Ma Thuột, Tân An, Tân Lập, Nguyễn Đại, Sông Cầu, Thống Nhất, Ea Kao, Tuy Hòa, Phú Yên, Bình Kiến, Đồng Hòa, Hòa Hiệp và các xã Hòa Phú, Xuân Thọ, Xuân Cảnh, Xuân Lộc, Hòa Xuân.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '24. Tỉnh Khánh Hòa', detail: 'Vùng II: gồm các phường Nha Trang, Bắc Nha Trang, Tây Nha Trang, Nam Nha Trang, Bắc Cam Ranh, Cam Ranh, Cam Linh, Bà Ngòi, Ninh Hòa, Đồng Ninh Hòa, Hòa Thắng, Phan Rang, Đồng Hải và nhiều xã lân cận.\nVùng III: gồm các xã Đại Lãnh, Tu Bông, Vạn Thắng, Vạn Ninh và nhiều xã khác.\nVùng IV: gồm các xã, phường và đặc khu còn lại.' },
    { name: '25. Tỉnh Gia Lai', detail: 'Vùng III: gồm các phường Quy Nhơn, Quy Nhơn Đông, Quy Nhơn Tây, Quy Nhơn Nam, Quy Nhơn Bắc, Pleiku, Hội Phú, Thống Nhất, Diên Hồng, An Phú và các xã Biển Hồ, Gào.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '26. Tỉnh Lâm Đồng', detail: 'Vùng II: gồm các phường Xuân Hương - Đà Lạt, Cam Ly - Đà Lạt, Làm Viên - Đà Lạt, Xuân Trường - Đà Lạt và nhiều phường khác.\nVùng III: gồm nhiều xã thuộc Đức Trọng, Di Linh, Bảo Lâm, Đạ Huoai và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '27. Thành phố Hồ Chí Minh', detail: 'Vùng III: gồm các xã Ngãi Giao, Bình Giã, Kim Long, Châu Đức, Xuân Sơn, Nghĩa Thành, Hòa Hiệp, Bình Châu, Hố Trầm, Xuyên Mộc và đặc khu Côn Đảo.\nVùng II: gồm các phường Bà Rịa, Long Hương, Tam Long và các xã Bình Khánh, An Thời Đông, Cần Giờ, Thạnh An; các xã Long Hải, Long Điền.\nVùng I: gồm các xã, phường còn lại.' },
    { name: '28. Tỉnh Đồng Nai', detail: 'Vùng I: gồm các phường Biên Hòa, Trản Biên, Tam Hiệp, Long Bình, Tràng Dài, Hố Nai, Long Hưng, Bình Lộc, Bảo Vinh, Xuân Lập, Long Khánh, Hàng Gòn và nhiều phường khác.\nVùng II: gồm các phường Minh Hưng, Chơn Thành, Đồng Xoài, Bình Phước và nhiều xã khác.\nVùng III: gồm các phường Thiên Hưng, Hưng Phước, Phú Nghĩa, Đa Kia và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '29. Tỉnh Tây Ninh', detail: 'Vùng I: gồm các phường Long An, Tân An, Khánh Hậu và nhiều xã lân cận.\nVùng II: gồm các phường Kiến Tường, Tân Ninh, Bình Minh, Ninh Thạnh, Long Hoa, Hòa Thành, Thanh Điền và nhiều xã khác.\nVùng III: gồm các xã Bình Thành, Thanh Phước, Thanh Hòa và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '30. Tỉnh Đồng Tháp', detail: 'Vùng II: gồm các phường Mỹ Tho, Đạo Thanh, Mỹ Phong, Thới Sơn, Trung An và nhiều xã lân cận.\nVùng III: gồm các phường Gò Công, Long Thuận, Bình Xuân và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '31. Tỉnh Vĩnh Long', detail: 'Vùng II: gồm các phường Thanh Đức, Long Châu, Phước Hậu, Tân Hạnh, Tân Ngãi, Bình Minh, Cái Vồn, Đồng Thành, An Hội và nhiều xã lân cận.\nVùng III: gồm các phường Duyên Hải, Trường Long Hòa và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '32. Tỉnh An Giang', detail: 'Vùng II: gồm các phường Long Xuyên, Bình Đức, Mỹ Thới, Châu Đốc, Vĩnh Tế, Vĩnh Thông, Rạch Giá, Hà Tiên và nhiều phường khác.\nVùng III: gồm nhiều xã thuộc Tân Châu, Châu Phú, Thoại Sơn, Kiên Giang và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '33. Thành phố Cần Thơ', detail: 'Vùng II: gồm các phường Phú Lợi, Mỹ Xuyên, Ninh Kiều, Cái Khế, Tân An, An Bình, Thới An Đông, Bình Thủy, Long Tuyến, Cái Răng, Hưng Phú, Ô Môn, Thới Long, Phước Thới, Trung Nhứt, Thốt Nốt, Thuận Hưng, Tân Lộc.\nVùng III: gồm nhiều xã thuộc Vị Thanh, Vị Tân, Đại Thành, Ngã Bảy, Vĩnh Châu, Khánh Hòa, Ngã Năm và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
    { name: '34. Tỉnh Cà Mau', detail: 'Vùng II: gồm các phường An Xuyên, Lý Văn Lâm, Tân Thành, Hòa Thành, Bạc Liêu, Vĩnh Trạch, Hiệp Thành.\nVùng III: gồm nhiều xã thuộc Giá Rai, Làng Trôn, Ú Minh, Nguyễn Phích, Khánh Lâm, Khánh An và nhiều xã khác.\nVùng IV: gồm các xã, phường còn lại.' },
];

function fmt(n) { return Math.round(n).toLocaleString('vi-VN'); }

export default function MinWageModal({ show, onClose, period, periodId }) {
    if (!show) return null;

    const provinceData = periodId === 'nd293' ? PROVINCES_ND293 : PROVINCES_ND73;

    return (
        <div
            style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 1000, display: 'flex', alignItems: 'flex-start', justifyContent: 'center', padding: '20px', overflowY: 'auto' }}
            onClick={e => { if (e.target === e.currentTarget) onClose(); }}
        >
            <div style={{ background: 'white', borderRadius: '12px', width: '100%', maxWidth: '700px', maxHeight: '80vh', display: 'flex', flexDirection: 'column', marginTop: '40px' }}>
                <div style={{ padding: '20px 24px 16px', borderBottom: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 }}>
                    <div>
                        <h3 style={{ fontSize: '16px', fontWeight: '700', color: '#111827', margin: 0 }}>Mức lương tối thiểu vùng</h3>
                        <p style={{ fontSize: '13px', color: '#6b7280', margin: '4px 0 0' }}>Áp dụng mức lương tối thiểu vùng mới nhất có hiệu lực từ ngày {period.minWageDate}</p>
                    </div>
                    <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: '22px', cursor: 'pointer', color: '#9ca3af', lineHeight: 1, padding: '4px 8px' }}>×</button>
                </div>

                <div style={{ padding: '16px 24px', borderBottom: '1px solid #e5e7eb', flexShrink: 0 }}>
                    <ul style={{ margin: 0, padding: '0 0 0 20px', fontSize: '14px', color: '#374151', lineHeight: 1.8 }}>
                        {['I', 'II', 'III', 'IV'].map(z => (
                            <li key={z}>Vùng {z}: <strong>{fmt(period.minWage[z])} đồng/tháng</strong></li>
                        ))}
                    </ul>
                </div>

                <div style={{ overflowY: 'auto', flex: 1, padding: '16px 24px' }}>
                    <p style={{ fontSize: '13px', color: '#dc2626', fontWeight: '600', marginBottom: '12px' }}>
                        Danh mục địa bàn cấp xã áp dụng mức lương tối thiểu vùng (áp dụng từ {period.minWageDate}):
                    </p>
                    {provinceData.map((prov, i) => (
                        <div key={i} style={{ marginBottom: '12px' }}>
                            <p style={{ fontWeight: '600', fontSize: '14px', color: '#111827', margin: '0 0 4px' }}>{prov.name}</p>
                            {prov.detail.split('\n').map((line, j) => (
                                <p key={j} style={{ fontSize: '13px', color: '#374151', margin: '0 0 2px', lineHeight: 1.6 }}>- {line}</p>
                            ))}
                        </div>
                    ))}
                </div>

                <div style={{ padding: '12px 24px', borderTop: '1px solid #e5e7eb', flexShrink: 0, textAlign: 'right' }}>
                    <button onClick={onClose} style={{ padding: '8px 24px', background: '#00b14f', color: 'white', border: 'none', borderRadius: '6px', fontSize: '14px', fontWeight: '600', cursor: 'pointer' }}>Đóng lại</button>
                </div>
            </div>
        </div>
    );
}
